### ISSUE TITLE
Command not found; is the pandoc-format processor installed?

### ISSUE THREAD

**Issue by IssaAboudi** [ritobanrc/mdbook-pandoc-format#1]
![image](https://user-images.githubusercontent.com/65807151/192193832-7f5d7e8b-e3ca-48c0-98c6-c599e6086695.png)

**Comment by ritobanrc** [comment]
The `mdbook-pandoc-format` executable needs to be in one of the folders of your `PATH` environment variable. The easiest way to do that is just to run `cargo install`, which should copy the binary `~/.cargo/bin`, which if it is in your `PATH`, `mdbook` should be able to access. 

Alternatively, you can do what I suggest in the README and symlink the `mdbook-pandoc-format` binary to `~/.local/bin` (but in hindsight, that's probably not a great idea, since there won't be any package managers managing the symlink).

**Comment by IssaAboudi** [comment]
Hey thanks now it builds fine - does give me a warning `Warning: The nop-preprocessor plugin was built against version 0.4.3 of mdbook, but we're being called from version 0.4.21` but im not sure that is affecting anything.

Items wrapped in $$ don't seem to be displaying correctly however. for example it still shows:

![image](https://user-images.githubusercontent.com/65807151/192198926-6666098a-d046-4cd5-a6b5-c2593fb67416.png)

**Comment by ritobanrc** [comment]
> Warning: The nop-preprocessor plugin was built against version 0.4.3 of mdbook, but we're being called from version 0.4.21

It shouldn't theoretically matter (since they are the same major version), but you should probably update `mdbook` (whether you installed it through your distro package manager, or by re-running `cargo install mdbook` if you installed it through cargo). 

> Items wrapped in $$ don't seem to be displaying correctly however. for example it still shows:

This crate does not do anything with math formatting. All it does is parse the pandoc-style YAML metadata at the top of a markdown file, convert the `title` field into a top-level heading, and shift all of the other headings down (its a rather niche usecase). If you want math formatting, you should use MathJax, probably following the instructions here: https://rust-lang.github.io/mdBook/format/mathjax.html

I'm closing the issue since you said that it builds fine (so the main issue has been addressed), but feel free to ask me any other questions.
