### ISSUE TITLE
Is there a binary out there?

### ISSUE THREAD

**Issue by rufus42** [ritobanrc/mdbook-pandoc-format#2]
Hello @ritobanrc,

sounds great!
Unfortunately I can't install Rust.
Is there a binary out there?

Thanks & greetings
rufus42

**Comment by ritobanrc** [comment]
I'm not going to distribute a binary, because to be perfectly frank, this project is not in a position where it is _usable_ at all. 

I haven't used it in over a year at this point, the code is _exceptionally_ poor quality (I wrote it in half a day, making some tiny changes from the `Nop` example from the mdbook tutorial, I haven't even changed the name of the struct). I can make no guarantees about what it does (frankly I don't even remember), and certainly don't have the time to maintain it. 

If you're interested in forking the code and modifying it, you are welcome to,  but I do not think this project is in a place where it can be distributed to people who are not comfortable in directly looking at and working with the code. For that matter, there isn't even any documentation telling you what the preprocessor actually does, you have to look at at the code and guess -- if you're not able to compile it yourself, you certainly should not be running it, because _there's no way for you to know what the code is actually doing_. 

I apologize, since this probably isn't what you wanted to hear -- but I hope you understand that I'm really saving you from more pain in the future. It almost certainly does not do what you want it to, and I'm not in a position where I can handle bug reports or other problems.

**Comment by rufus42** [comment]
Hello Ritoban @ritobanrc ,

Thank you very much for your nice reply and your offer to continue working on your code.

Unfortunately, I am not a developer.
I can't work on the code.

I understand that you don't provide binary for an "unfinished program".

Thank you very much for your time to answer me.

Many kind regards
rufus 42

P.S.: Please excuse me for abusing this channel again.... I can't answer you by e-mail, but I wanted to answer you with pleasure
